{% set name = "feast" %}
{% set version = "0.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/feast-{{ version }}.tar.gz
  sha256: 6534686726da621aa9f15523dd2b0a1532cfa64bef3af0b9d046f6388e3bac6a

build:
#  skip: true  # [py<37 or py>10]
#  skip: True  # [win or osx]
  noarch: python
  entry_points:
    - feast=feast.cli:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  #build:
    #- {{ compiler('c') }}
    #- python >=3.7,<3.11
  host:
    - python >=3.7
    - setuptools >=60
    - wheel
    - setuptools-scm >=6.2
    - grpcio
    - grpcio-tools >=1.47.0
    - mypy-protobuf ==3.1
    - sphinx !=4.0.0
    - pybindgen ==0.22.1
    - pip
  run:
    - python >=3.7
    - click >=7.0.0,<9.0.0
    - colorama >=0.3.9,<1
    - dill >=0.3.0,<0.4.0
    - fastavro >=1.1.0,<2
    #- google-api-core >=1.23.0,<3
    #- googleapis-common-protos >=1.52.*,<2
    - grpcio >=1.41.1,<2
    - grpcio-reflection >=1.41.1,<2
    - jinja2 >=2,<4
    - jsonschema
    - mmh3
    - numpy >=1.21,<3
    - pandas >=1.3.5,<2
    - pandavro >=1.5.0,<1.6.0
    - protobuf >3.0,<5.0
    - proto-plus >=1.20.0,<2
    - pyarrow >=4,<13
    - pydantic >=1,<2
    - pygments >=2.12.0,<3
    - pyyaml >=5.4.0,<7
    - requests
    - sqlalchemy >1,<2
    - tabulate >=0.8.0,<1
    - tenacity >=7,<9
    - toml >=0.10.0,<1
    - tqdm >=4,<5
    - typeguard
    - fastapi >=0.66.0,<1
    - uvicorn >=0.14.0,<1
    - gunicorn
    - dask-core >=2021.1.0
    - bowler
    - httpx >=0.23.3

test:
  imports:
    - feast
  commands:
    - feast --help
  requires:
    - pip

about:
  home: https://github.com/feast-dev/feast
  summary: Python SDK for Feast
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
